.TH EDLIN 1 "version 0.9" "September 2024"
.SH NAME
edlin \- a simple text editor
.SH SYNOPSIS
edlin [file]
.SH DESCRIPTION
edlin is a simple text editor inspired by MS-DOS edlin.
.SH EDITING
Edlin is an interactive editor, commands are entered at the prompt.
.SH OPTIONS
Pass the name of the file to edit.
.SH SEE ALSO
https://github.com/rhubarb-geek-nz/edlin
.SH AUTHOR
Roger Brown (rhubarb-geek-nz@users.sourceforge.net)
