#define EDLMESEN_EOF "End of input file\r\n"
#define EDLMESEN_PROMPT "*"
#define EDLMESEN_QMES "Abort edit (Y/N)? "
#define EDLMESEN_BADCOM "Entry error\r\n"
#define EDLMESEN_ESCAPE "\\\r\n"
#define EDLMESEN_CTRLC "^C\r\n\r\n"
#define EDLMESEN_NDNAME "File name must be specified\r\n"
#define EDLMESEN_NOSUCH "Not found.\r\n"
#define EDLMESEN_ASK "O.K.? "
#define EDLMESEN_MRGERR "Not enough room to merge the entire file\r\n"
#define EDLMESEN_MEMFUL "Insufficient memory\r\n"
#define EDLMESEN_TOOLNG "Line too long\r\n"
#define EDLMESEN_NEWFIL "New file\r\n"
#define EDLMESEN_NN "Nn"
#define EDLMESEN_YY "Yy"
#define EDLMESEN_NOBAK "Cannot edit .BAK file--rename file\r\n"
#define EDLMESEN_DEST "Must specify destination line number\r\n"
