#!/bin/sh -e
# Copyright (c) 2024 Roger Brown.
# Licensed under the MIT License.

if grep '^#define HAVE_LIBINTL_H 1$' config.h > /dev/null
then
	:
else
	echo >&2 Should be using GNU gettext
	false
fi

VERSION=$( . ./version ; echo $VERSION )
PKGNAME=edlin

cleanup()
{
	rm -rf root MANIFEST PLIST
}

trap cleanup 0

cleanup

mkdir -p root/usr/local/bin root/usr/local/man/man1

cp edlin root/usr/local/bin
strip root/usr/local/bin/edlin
gzip < edlin.1 > root/usr/local/man/man1/edlin.1.gz

for A in de en es fr it
do
	mkdir -p "root/usr/local/share/locale/$A/LC_MESSAGES"
	msgfmt -o "root/usr/local/share/locale/$A/LC_MESSAGES/edlin.mo" "posix/nls/edlin-$A.po"
done

cat > MANIFEST <<EOF
name $PKGNAME
version $VERSION
desc "Simple, interactive, command line text editor."
www https://github.com/rhubarb-geek-nz/edlin
origin editors/edlin
comment Text Editor based on MS-DOS edlin
maintainer rhubarb-geek-nz@users.sourceforge.net
prefix /usr/local
EOF

(
	cd root/usr/local
	find * -type f -name "edlin*"
) > PLIST

pkg create -M MANIFEST -o . -r root -v -p PLIST
