#!/bin/sh -e
# Copyright (c) 2024 Roger Brown.
# Licensed under the MIT License.

cleanup()
{
	rm -rf data rpms rpm.spec
}

umask 022

cleanup

trap cleanup 0

VERSION=$( . ./version ; echo $VERSION )
PWD=$(pwd)
PKGNAME=edlin

mkdir -p data/usr/bin rpms "data/usr/share/doc/$PKGNAME" "data/usr/share/man/man1"

cp edlin data/usr/bin

strip data/usr/bin/edlin

sed --quiet < src/edlin.c '/\*\*\*\*/,/^ \*\//p' | grep -v '\*\*\*' | grep -v '^ \*/' | while read A B
do
	echo "$B"
done | ( 
	while read A
	do
		if test -n "$A"
		then
			echo "$A"
			break
		fi
	done
	cat 
) > "data/usr/share/doc/$PKGNAME/copyright"

if git config --get remote.origin.url
then
	(
		set -e
		git config --get remote.origin.url
		TZ=UTC git log --oneline src/edlin.c
	) > "data/usr/share/doc/$PKGNAME/changelog"
else
	if svn info .
	then
		(
			set -e
			svn info . | grep "^URL: " | while read A B
			do
				echo "$B"
			done
			TZ=UTC svn log src/edlin.c
		) > "data/usr/share/doc/$PKGNAME/changelog"
	fi
fi

if test -f "data/usr/share/doc/$PKGNAME/changelog"
then
	gzip "data/usr/share/doc/$PKGNAME/changelog"
fi

gzip < README.md > "data/usr/share/doc/$PKGNAME/README.md.gz"
gzip < edlin.1 > "data/usr/share/man/man1/edlin.1.gz"

if dpkg --print-architecture 2>/dev/null
then
	DPKGARCH=$(dpkg --print-architecture)
	SIZE=$(du -sk data/usr/bin/edlin | while read A B; do echo $A; done)
	mkdir data/DEBIAN
	cat > data/DEBIAN/control <<EOF
Package: $PKGNAME
Version: $VERSION
Architecture: $DPKGARCH
Installed-Size: $SIZE
Maintainer: rhubarb-geek-nz@users.sourceforge.net
Section: editors
Priority: extra
Description: Text Editor based on MS-DOS edlin
 Simple, interactive, command line text editor.
 .
EOF

	dpkg-deb --root-owner-group --build data "$PKGNAME"_"$VERSION"_"$DPKGARCH".deb

	rm -rf data/DEBIAN
fi

if rpmbuild --version 2>/dev/null
then
	cat > rpm.spec <<EOF
Summary: edlin editor
Name: edlin
Version: $VERSION
Release: 1
Group: Applications/System
License: MIT
Prefix: /usr

%description
Text editor based on MS-DOS edlin

%files
%defattr(-,root,root)
%attr(755,root,root) /usr/bin/edlin

%clean
EOF

	rpmbuild --buildroot "$PWD/data" --define "_rpmdir $PWD/rpms" --define "_build_id_links none" -bb "$PWD/rpm.spec" 

	find rpms -name "*.rpm" -type f | while read N
	do
		mv "$N" .
	done
fi
