#!/bin/sh -e
# Copyright (c) 2024 Roger Brown.
# Licensed under the MIT License.

VERSION=$( . ./version ; echo $VERSION )
PKGNAME="edlin-$VERSION.tgz"

cleanup()
{
	rm -rf root meta unsigned edlin-$VERSION-pkg.sec
}

trap cleanup 0

cleanup

mkdir -p root/usr/local/bin root/usr/local/man/man1 meta unsigned

cp edlin root/usr/local/bin
strip root/usr/local/bin/edlin
cp edlin.1 root/usr/local/man/man1

for A in de en es fr it
do
	mkdir -p "root/usr/local/share/locale/$A/LC_MESSAGES"
	gencat "root/usr/local/share/locale/$A/LC_MESSAGES/edlin.cat" "posix/nls/edlin-$A.msg"
done

(
	set -e
	cd root
	find usr/local -type f -name "edlin*"
) > meta/CONTENTS

echo "Text Editor based on MS-DOS edlin" >"meta/COMMENT"

cat >"meta/DESC" <<EOF
Simple, interactive, command line text editor.
EOF

COMMENT="Text Editor based on MS-DOS edlin"
MACHINE_ARCH=$(uname -p)
HOMEPAGE=https://github.com/rhubarb-geek-nz/edlin
MAINTAINER=rhubarb-geek-nz@users.sourceforge.net
FULLPKGPATH=editors/edlin
FTP=yes

pkg_create \
		-A "$MACHINE_ARCH"\
		-d meta/DESC \
		-D "COMMENT=$COMMENT" \
		-D "HOMEPAGE=$HOMEPAGE" \
		-D "MAINTAINER=$MAINTAINER" \
		-D "FULLPKGPATH=$FULLPKGPATH" \
		-D "FTP=$FTP" \
		-f meta/CONTENTS \
		-B root \
		-p / \
		"unsigned/$PKGNAME"

signify -G -n -c "edlin-$VERSION package" -s edlin-$VERSION-pkg.sec -p edlin-$VERSION-pkg.pub

pkg_sign -s signify2 -s edlin-$VERSION-pkg.sec -o . -S unsigned
