#!/bin/sh -e
# Copyright (c) 2024 Roger Brown.
# Licensed under the MIT License.

VERSION=$( . ./version ; echo $VERSION )
PKGNAME="edlin-$VERSION.tgz"
ISMSGFMT=false
ISGENCAT=false
PREFIX=/usr/local

if grep '^#define HAVE_LIBINTL_H 1$' config.h > /dev/null
then
	ISMSGFMT=true
else
	if grep '^#define HAVE_NL_TYPES_H 1$' config.h > /dev/null
	then
		ISGENCAT=true
	fi
fi

cleanup()
{
	rm -rf root meta unsigned edlin-$VERSION-pkg.sec
}

trap cleanup 0

cleanup

mkdir -p root$PREFIX/bin root$PREFIX/man/man1 meta unsigned

cp edlin root$PREFIX/bin
strip root$PREFIX/bin/edlin
cp edlin.1 root$PREFIX/man/man1

if $ISMSGFMT
then
	for A in de en es fr it
	do
		mkdir -p "root$PREFIX/share/locale/$A/LC_MESSAGES"
		msgfmt -o "root$PREFIX/share/locale/$A/LC_MESSAGES/edlin.mo" "posix/nls/edlin-$A.po"
	done
fi

if $ISGENCAT
then
	for d in de_DE es_ES fr_FR it_IT
	do
		SHORT=$(echo $d | sed y/_/\ / | while read A B; do echo $A; done )
		mkdir -p "root$PREFIX/share/nls/$d.UTF-8"
		gencat "root$PREFIX/share/nls/$d.UTF-8/edlin.cat" "posix/nls/edlin-$SHORT.msg"
	done
fi

(
	set -e
	cd root
	find usr/local -type f -name "edlin*"
) > meta/CONTENTS

echo "Text Editor based on MS-DOS edlin" >"meta/COMMENT"

cat >"meta/DESC" <<EOF
Simple, interactive, command line text editor.
EOF

COMMENT="Text Editor based on MS-DOS edlin"
MACHINE_ARCH=$(uname -p)
HOMEPAGE=https://github.com/rhubarb-geek-nz/edlin
MAINTAINER=rhubarb-geek-nz@users.sourceforge.net
FULLPKGPATH=editors/edlin
FTP=yes

pkg_create \
		-A "$MACHINE_ARCH"\
		-d meta/DESC \
		-D "COMMENT=$COMMENT" \
		-D "HOMEPAGE=$HOMEPAGE" \
		-D "MAINTAINER=$MAINTAINER" \
		-D "FULLPKGPATH=$FULLPKGPATH" \
		-D "FTP=$FTP" \
		-f meta/CONTENTS \
		-B root \
		-p / \
		"unsigned/$PKGNAME"

signify -G -n -c "edlin-$VERSION package" -s edlin-$VERSION-pkg.sec -p edlin-$VERSION-pkg.pub

pkg_sign -s signify2 -s edlin-$VERSION-pkg.sec -o . -S unsigned
