#!/bin/sh -e
# Copyright (c) 2024 Roger Brown.
# Licensed under the MIT License.

VERSION=$( . ./version ; echo $VERSION )
PWD=$(pwd)
APPNAME=edlin
PKGNAME=RHBedlin
DESCRIPTION="Text Editor based on MS-DOS edlin"
INTDIR="$PWD/data"
PKGROOT="$INTDIR/pkgroot"
PKGTMP="$INTDIR/pkgtmp"

cleanup()
{
	rm -rf "$INTDIR"
}

umask 022

cleanup

trap cleanup 0

mkdir -p "$PKGROOT/bin" "$PKGROOT/share/man/man1" "$PKGTMP"

cp "$APPNAME" "$PKGROOT/bin"
cp "$APPNAME.1" "$PKGROOT/share/man/man1"

if grep '^#define HAVE_LIBINTL_H 1$' config.h > /dev/null
then
	for d in de en es fr it
	do
		mkdir -p "$PKGROOT/share/locale/$d/LC_MESSAGES"
		msgfmt -o "$PKGROOT/share/locale/$d/LC_MESSAGES/edlin.mo" "posix/nls/edlin-$d.po"
	done
else
	for d in de en es fr it
	do
		locale -a | grep "^$d"_  | grep ".ISO8859-1\$" | while read L
		do
			if test ! -d  "$PKGROOT/lib/locale/$d/LC_MESSAGES"
			then
				mkdir -p "$PKGROOT/lib/locale/$d/LC_MESSAGES"
				LANG="$L" ./readutf8 "posix/nls/edlin-$d.msg" | grep -v "codeset=utf-8" > "edlin-$d.msg"
				LANG="$L" gencat "$PKGROOT/lib/locale/$d/LC_MESSAGES/edlin" "edlin-$d.msg"
				rm "edlin-$d.msg"
			fi
		done
	done
fi

if file edlin | grep " AMD64 "
then
	PKGARCH=amd64
else
	PKGARCH=$(uname -p)
fi

PKGFILE="$PKGNAME-$VERSION-$PKGARCH.pkg"

rm -rf "$PKGFILE"

(
	echo "ARCH=\"$PKGARCH\""
	echo "CATEGORY=\"utility\""
	echo "NAME=\"$DESCRIPTION\""
	echo "PKG=\"$PKGNAME\""
	echo "VERSION=\"$VERSION\""
	echo "BASEDIR=\"/usr\""
) >"$INTDIR/pkginfo"

(
	echo i pkginfo
	echo d none "bin" 0755 root bin
	echo f none "bin/$APPNAME" 0755 root bin
	echo d none "share" 0755 root sys
	echo d none "share/man" 0755 root bin
	echo d none "share/man/man1" 0755 root bin
	echo f none "share/man/man1/$APPNAME.1" 0444 root bin
	(
		cd "$PKGROOT"
		find share/locale -type d | while read N
		do
			echo d none "$N" 0755 root other
		done
		find share/locale -type f -name edlin.mo | while read N
		do
			echo f none "$N" 0444 root other
		done
		find lib -type d | while read N
		do
			echo d none "$N" 0755 root bin
		done
		find lib -type f -name edlin | while read N
		do
			echo f none "$N" 0444 root bin
		done
	)
) >"$INTDIR/prototype"

pkgmk -o -r "$PKGROOT" -d "$PKGTMP" -f "$INTDIR/prototype" "$PKGNAME"

touch "$PKGFILE"

pkgtrans -s "$PKGTMP" "$PKGFILE" "$PKGNAME"

pkginfo -l -d "$PKGFILE"
